export const URLS = {
  whatsapp: "https://wa.me/551148584125?text=Ol%C3%A1%20Unbox!",
  demo: "https://bit.ly/Unbox-Growth",
  signup: "https://admin.unbox.com.br/cadastro",
  login: "https://admin.unbox.com.br/",
  industriaApply: "#habilitar-industria",
};

export const LEADS = { sheetWebhook: "" };

// Maps the old window.__resources IDs to public paths
export const R = {
  "instagram": "/img/instagram.svg",
  "youtube": "/img/youtube.svg",
  "facebook": "/img/facebook.svg",
  "linkedin": "/img/linkedin.svg",
  "logo-unbox": "/img/logo-unbox.svg",
  "logo-unbox-roxo": "/img/logo-unbox.svg",
  "logo-navbar": "/img/logo-navbar.png",
  "print-menu": "/img/print-menu.png",
  "Glow": "/img/Glow.png",
  "logo-sunrize": "/img/sunrize-logo.png",
  "logo-wish": "/img/wish-logo.png",
  "logo-pudim": "/img/pudim-logo.png",
  "Bhava": "/img/Bhava.png",
  "assinatura2": "/img/assinatura2.png",
  "checkout-dash": "/img/checkout-dash.png",
  "checkout-card": "/img/checkout-card.png",
  "Sunrize": "/img/Sunrize.png",
  "Badia": "/img/Badia.png",
  "logo-badia": "/img/badia-logo.svg",
  "Noway": "/img/Noway.png",
  "OLEA": "/img/OLEA.png",
  "dicapri-foto": "/img/dicapri-foto.png",
  "assinatura": "/img/assinatura.png",
  "video-gaafer": "/img/depoimento-gaafer.mp4",
  "loja-dicapri": "/img/loja-dicapri.png",
  "loja-pudim": "/img/loja-pudim.png",
  "loja-popai": "/img/loja-popai.png",
  "loja-vistapere": "/img/loja-vistapere.png",
  "loja-olea": "/img/loja-olea.png",
  "pudim-transp": "/img/pudim-transp.png",
  "hero-bhava": "/img/hero-bhava.png",
  "hero-glow": "/img/hero-glow.png",
  "hero-badia": "/img/hero-badia.png",
  "hero-popai": "/img/hero-popai.png",
  "hero-pudim": "/img/hero-pudim.png",
  "feat-ecommerce": "/img/feat-ecommerce.png",
  "feat-checkout": "/img/feat-checkout.png",
  "checkout-hero": "/img/checkout-hero.png",
  "feat-assinatura": "/img/feat-assinatura.png",
  "feat-creators": "/img/feat-creators.png",
  "feat-unboxpay": "/img/feat-unboxpay.png",
  "feat-promocoes-wide": "/img/feat-promocoes-wide.png",
  "feat-integrado-wide": "/img/feat-integrado-wide.png",
  "feat-sampling": "/img/feat-sampling.png",
  "feat-promocoes": "/img/feat-promocoes.png",
  "feat-creator-link": "/img/feat-creator-link.png",
  "feat-assinatura-sq": "/img/feat-assinatura-sq.png",
  "feat-upsell": "/img/feat-upsell.png",
  "feat-bundle": "/img/feat-bundle.png",
  "feat-pudim-mobile": "/img/feat-pudim-mobile.png",
  "feat-layout-admin": "/img/feat-layout-admin.png",
  "feat-lighthouse": "/img/feat-lighthouse.png",
  "credito-hero": "/img/credito-hero.mp4",
  "credito-hero-video": "/img/credito-hero.mp4",
  "brigadeiro-wish": "/img/brigadeiro-wish.png",
  "logo-shopify": "/img/logo-shopify.png",
  "logo-vtex": "/img/logo-vtex.png",
  "logo-woocommerce": "/img/logo-woocommerce.png",
  "team-1": "/img/team-1.png",
  "team-2": "/img/team-2.png",
  "team-3": "/img/team-3.png",
  "product-batom": "/img/product-batom.jpg",
  "product-colageno": "/img/product-colageno.jpg",
  "product-creatina": "/img/product-creatina.jpg",
  "product-whey": "/img/product-whey.jpg",
};
