// jobsData.js — vagas abertas (geradas do CSV do Webflow, filtradas: publicadas e não arquivadas).
// Growth Hunter e Líder de Operações desativadas temporariamente. Campo "tipo" (Tempo integral) removido a pedido.
export const JOBS = [
 {
  "name": "Analista de Atendimento",
  "slug": "analista-de-atendimento",
  "overview": "Estamos em busca de uma pessoa que goste de fazer atividades para melhorar a experiência dos clientes e, assim, criar relacionamentos incríveis com eles e (de bônus) com o nosso time de Unboxers. 💜",
  "area": "Marketing",
  "local": "Remoto",
  "novo": true,
  "apply": "https://www.unbox.com.br/unbox-trabalhe-conosco",
  "body": "<p id=\"\"><strong id=\"\">Analista de Atendimento</strong></p><p id=\"\">Se você é uma pessoa #inquieta e topa o desafio de escalar a empresa de tecnologia que está reinventando a forma de vender online no Brasil, junte-se a nós e venha empoderar milhares de pequenas e médias empresas por todo o país.</p><p id=\"\">Procuramos pessoas apaixonadas, que queiram crescer junto com a Unbox e que entendam a importância de fazer parte desse momento da empresa. Estamos construindo um time diverso, inclusivo e respeitoso.</p><p id=\"\"><strong id=\"\">‍</strong></p><p id=\"\"><strong id=\"\">Como Analista de Atendimento, o que você irá fazer?</strong>  </p><p id=\"\">Dar a melhor experiência para o cliente com um atendimento via chat, whatsapp e e-mail, dando suporte e sendo uma ponte entre outras áreas.   </p><p id=\"\">Coletar, organizar e reportar feedbacks recebidos no atendimento e compartilhar com outros times;  </p><p id=\"\">Foco e agilidade em melhoria de processos;  </p><p id=\"\">Trazer ideias de como podemos melhorar o que já fazemos hoje;  </p><p id=\"\">  </p><p id=\"\"><strong id=\"\">Qual o perfil que buscamos?</strong>  <br></p><ul id=\"\"><li id=\"\">Organização, disciplina, flexibilidade e muita vontade de aprender não podem faltar!   </li><li id=\"\">Pessoas confortáveis com uma dinâmica de trabalho mão na massa;   </li><li id=\"\">Pessoas com domínio da linguagem escrita; &nbsp;</li><li id=\"\">Pessoas comunicativas e proativas;  </li><li id=\"\">Com experiência em atendimento ao cliente em plataformas de e-commerce ou startups;</li></ul><p id=\"\"><strong id=\"\">Venha conversar com a gente se você:</strong></p><ul id=\"\"><li id=\"\">Ficar motivado pelo propósito da Unbox e ser apaixonado por pessoas, entendendo que tudo o que estamos construindo é por elas e para elas!</li><li id=\"\">Experiência em atendimento e encantamento de clientes.</li><li id=\"\">Fluência e coesão na comunicação escrita em Português.</li><li id=\"\">Fortes habilidades de comunicação.</li><li id=\"\">Capacidade de trabalhar em um ambiente dinâmico e orientado a resultados.</li><li id=\"\">Conhecimento em ferramentas de atendimento. </li></ul><p id=\"\"><strong id=\"\">‍</strong></p><p id=\"\"><strong id=\"\">Melhor ainda se você:</strong></p><ul id=\"\"><li id=\"\">Experiência prévia com SaaS para PMEs no mercado brasileiro</li><li id=\"\">Familiaridade com metodologias de vendas modernas e ferramentas de prospecção.</li></ul><p id=\"\"><strong id=\"\">‍</strong></p><p id=\"\"><strong id=\"\">O que temos para você?</strong></p><ul id=\"\"><li id=\"\">Salário compatível com o mercado em contratação PJ</li><li id=\"\">Trabalho Remoto </li><li id=\"\">Gympass</li><li id=\"\">Cartão de Benefícios Flexível  </li><li id=\"\">Plano de Saúde  </li></ul>"
 }
];
